##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Apr 5 22:33:28 2022
##  Generated by MIG Version 4.0
##  
##################################################################################################
##  File name :       example_top.sdc
##  Details :     Constraints file
##                    FPGA Family:       ZYNQ
##                    FPGA Part:         XC7Z020ICLG484_PKG
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-125
## Data Width: 8
## Time Period: 2500
## Data Mask: 1
##################################################################################################

create_clock -period 2 [get_ports sys_clk_p]
          
create_clock -period 5 [get_ports clk_ref_p]
          
############## NET - IOSTANDARD ##################


