# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lorenzogomez/half_adder/half_adder.cache/wt [current_project]
set_property parent.project_path /home/lorenzogomez/half_adder/half_adder.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
add_files /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/design_ps_pl.bd
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_processing_system7_0_0/design_ps_pl_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_gpio_0_0/design_ps_pl_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_gpio_0_0/design_ps_pl_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_gpio_0_0/design_ps_pl_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_gpio_1_0/design_ps_pl_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_gpio_1_0/design_ps_pl_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_gpio_1_0/design_ps_pl_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_rst_processing_system7_0_100M_0/design_ps_pl_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_rst_processing_system7_0_100M_0/design_ps_pl_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_rst_processing_system7_0_100M_0/design_ps_pl_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_xbar_0/design_ps_pl_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_auto_pc_0/design_ps_pl_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/design_ps_pl_ooc.xdc]
set_property is_locked true [get_files /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/design_ps_pl.bd]

read_verilog -library xil_defaultlib /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/bd/design_ps_pl/hdl/design_ps_pl_wrapper.v
read_vhdl -library xil_defaultlib /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/new/half_adder.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lorenzogomez/half_adder/half_adder.srcs/constrs_1/imports/digilent-xdc/Zedboard-Master.xdc
set_property used_in_implementation false [get_files /home/lorenzogomez/half_adder/half_adder.srcs/constrs_1/imports/digilent-xdc/Zedboard-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_ps_pl_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_ps_pl_wrapper.dcp

catch { report_utilization -file design_ps_pl_wrapper_utilization_synth.rpt -pb design_ps_pl_wrapper_utilization_synth.pb }
