# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/lorenzogomez/half_adder/half_adder.cache/wt [current_project]
set_property parent.project_path /home/lorenzogomez/half_adder/half_adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
read_vhdl -library xil_defaultlib /home/lorenzogomez/half_adder/half_adder.srcs/sources_1/new/half_adder.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lorenzogomez/half_adder/half_adder.srcs/constrs_1/imports/digilent-xdc/Zedboard-Master.xdc
set_property used_in_implementation false [get_files /home/lorenzogomez/half_adder/half_adder.srcs/constrs_1/imports/digilent-xdc/Zedboard-Master.xdc]


synth_design -top half_adder -part xc7z020clg484-1


write_checkpoint -force -noxdef half_adder.dcp

catch { report_utilization -file half_adder_utilization_synth.rpt -pb half_adder_utilization_synth.pb }
